### ISSUE TITLE
觀影心得回饋

### ISSUE THREAD

**Issue by azole** [yuhyea1/yuhyea1#1]
謝謝你的影片心得，你整理得很好，每個人都有自己的節奏，但為自己找到合適的方法這件事，是自己的責任，希望這部影片可以幫助到你，從你的文字中，感受到你對自己不是很有信心，但卻是一個很有毅力的人，像你所說的，終究是會一點點地進步的，但要撐過某個瓶頸點，就不是每個人可以做到的，相信你是可以的。

上課有任何問題都即時發問，我非常非常非常地歡迎，很多時候，其他同學不問，不見得是沒有問題，更多可能是，還沒想到原來有這個問題，你能主動幫同學問出來的話，那真的就太棒了！所以，作為你們這門課的老師，我想拜託你，有問題就問，需要等一下解釋的，我會安排，適合立即解釋的，我就會立即解釋，這樣好嗎？

**Comment by azole** [comment]
我看到你分享的滑雪主題了，我從來沒有去滑過雪，總是聽朋友說，去日本的滑雪山莊，滑完一整天的雪，腰痠背痛，晚上再好好的泡個溫泉，隔天立刻又可以繼續玩，覺得超棒的，本來去年想要去的，可惡的肺炎，希望可以盡快出國去體驗一次滑雪看看！

關於課程跟上課，遇到突發狀況都是難免的，我想你當時一定很著急，但第二天你還是很努力地跟課，在教學上，我的心情一直是，只要你們想學，我就一定奉陪到底，所以，只要你很努力，我就會跟你一起加油的。

**Comment by yuhyea1** [comment]
非常感謝老師給我的鼓勵，我會繼續努力的，我會努力地完成老師所教的東西，也會盡力去多做練習，我們組內有位同學之前在學場上班過，他對於滑雪有一番的研究，自從專題開始接觸到滑雪後也對於滑雪頗感興趣的，希望之後有工作後會能有機會也出國去滑一次，但是聽說第一次滑雪會跌跌撞撞的，超痛的，老師到時候要做好心理準備唷哈哈哈，之後再麻煩老師了~
